### ISSUE TITLE
Exception has occurred. MissingPluginException (MissingPluginException(No implementation found for method getResourceUsage on channel resource_monitor))

### ISSUE THREAD

**Issue by ggencer** [sikandernoori/resource_monitor#1]
I'm getting this error. Could you please check the issue?

![image](https://user-images.githubusercontent.com/41690116/149091889-ccdb16ce-79d0-44bb-b2a9-cb1530611714.png)

best regards.

**Comment by LeonTenorio** [comment]
same problem here

**Comment by sikandernoori** [comment]
Please check Readme file:
Android side is still under construction.
If you implement do open PR.
