### ISSUE TITLE
Android exception

### ISSUE THREAD

**Issue by crismesy** [sikandernoori/resource_monitor#2]
No implementation found for method getResourceUsage on channel resource_monitor

**Comment by sikandernoori** [comment]
@crismesy I haven't got the time to Implement Android side of plugin.

[here](https://github.com/sikandernoori/resource_monitor/blob/0448224721b91cb7b18ce912f46ca72eb6ffb54a/android/src/main/kotlin/com/randomforest/resource_monitor/ResourceMonitorPlugin.kt#L21)

Feel free to open PR.
