### ISSUE TITLE
Android error

### ISSUE THREAD

**Issue by a42279395** [sikandernoori/resource_monitor#3]
MissingPluginException (MissingPluginException(No implementation found for method getResourceUsage on channel resource_monitor))

**Comment by AmeerSafdar** [comment]
same error with me

**Comment by sikandernoori** [comment]
Android side not implemented yet.

Feel free to open PR.

https://github.com/sikandernoori/resource_monitor/blob/0448224721b91cb7b18ce912f46ca72eb6ffb54a/android/src/main/kotlin/com/randomforest/resource_monitor/ResourceMonitorPlugin.kt#L20
