### ISSUE TITLE
Exception has occured.

### ISSUE THREAD

**Issue by AmeerSafdar** [sikandernoori/resource_monitor#4]
MissingPluginException (MissingPluginException(No implementation found for method getResourceUsage on channel resource_monitor))

**Comment by sikandernoori** [comment]
@AmeerSafdar Are you running it on Android ?

**Comment by sikandernoori** [comment]
Android side is not implemented yet.

https://github.com/sikandernoori/resource_monitor/blob/0448224721b91cb7b18ce912f46ca72eb6ffb54a/android/src/main/kotlin/com/randomforest/resource_monitor/ResourceMonitorPlugin.kt#L20

Feel free to open PR.
